# Site
repository: KamalBarati/KamalBarati.github.io.
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kamal Barati
title: CS Student
email: barati.k21@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  KamalBarati
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: barati.k21
linkedin_username: kamalbarati
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# title: Link name
  #icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  #url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")
#
content:
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Allameh Tabataba’i University (ATU), Tehran
        sub_title:  M.Sc. in Computer Science
        caption: Spring 2021 to Present
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
          
      - layout: top-middle
        title: Isfahan University of Technology (IUT), Isfahan
        sub_title:  B.Sc. in Electrical Engineering - Communications
        caption: Fall 2013 to 2018
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification  
        
  - title: Honors and Awards
    #icon: fab fa-brophy
    layout: list
    content:
      - layout: top-middle
        title: 3rd Rank of National Khwarizmi Youth Award
        sub_title: Mathematics, Game Theory
        caption: Nov. 2012
        
      - layout: top-middle
        title: Member of the National Elite Foundation of Iran
        caption: Since 2013
        
      - layout: top-middle
        title: Brilliant Talent Scholarship Award
        sub_title:  Isfahan University of Technology (IUT)
        caption: 2014
        
  - title: Publications and Patents
    layout: text
    content: |
      - K. Barati, “How Can a Game Make an Educational Situation,” Iranian Mathematics Education Conference, Feb. 18, 2018, Bushehr, Iran.
      - F. Ahmadpour, Sh. Dastjerdi, K. Barati, “Modeling Problems, a Place for Citizenship Education,” Iranian Curriculum Studies Association Conference, 2018, Zanjan, Iran.
      - K. Barati, S. Shahsavari “Game Assembling on a Network,” A Mathematics Article for the National Khwarizmi Youth Festival, 2012, Tehran, Iran.
      - K. Barati, “Joft-o-Joor”, Persian Patent No. 95/0262409/3, Isuued May. 1, 2016.
        
              
  - title: Professional Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Research and Development Manager
        sub_title: Gostaresh Tejarat Golshan, Isfahan
        caption: Sep. 2020 - May 2021
        layout: text
        description: |
            - Data-driven Marketing
            - R Programming
            - Research on the Hardening and Coating Process of Steel

        
      - layout: top-middle
        title: Electrical Engineer 
        sub_title: Moein Zist Aria Co., Isfahan
        caption: Jan. 2016 - Sep.2020
        layout: text
        description: |
            - Design and Develop a Water Desalination System based on Thermoelectric Modules
            - PLC Programming and Process Automation of Zero Liquid Discharge (ZLD) Project Ordered by the Marun Petrochemical Complex.
      
        
      - layout: top-middle
        title:  Teaching Assistant
        sub_title: Isfahan University of Technology
        caption: Spring 2017 - Fall 2018
        layout: text
        description: |
            - Computer Networks_Spring 2017, Dr. Naghmeh S. Moayedian        
            - Fundamentals of Computer Programming_Fall 2018, Dr. Behzad Nazari 
            - Principles of Communication Systems_Fall 2018, Dr. Ehsan Yazdian 
            - C/C++ Programming Lab Instructor(Fall 2018)
      
      - layout: top-middle
        title:   Mathematics Teacher
        sub_title: Isfahan Mathematics House
        caption: Sep. 2013 - Present
        layout: text
        description: |
            - Tutoring Mathematics Workshops for Students and Teachers (Under the Supervision of Dr. Ali Rejali)
            - Mentor of Design Thinking Workshops Based on Stanford Method and POLY UP Workshops (under the Supervision of Dr. Yahya Tabesh)
            - Jury Member of Iran Mathematics A-Lympiad (Fall 2014 - 2020)
            - Paper Reviewer of Iran MathematicsTournament of Towns (Fall 2013 - 2020)
            - Scientific Consultant of Training Camp for Selected Students of the Iran Mathematics Tournament of Towns (Fall 2015 - 2018).

   
  - title: Skills
    layout: list
    content:
      - layout: top-middle
        title: Programing
        sub_title: C/C++, Python, R, Verilog/VHDL, SQL
        
      - layout: top-middle
        title: Applications
        sub_title: Machine Learning, Qt, MATLAB, LaTeX, GIT, SIMATIC, Adobe (Photoshop, Premiere)
        
      - layout: top-middle
        title: Language 
        sub_title: English, Persian (Native), Arabic (Basic)      

  - title: A Little More About Me
    layout: text
    content: | 
        Alongside my interests in CS, some of my other interests and hobbies are:
        - Doing Gymnastics
        - Playing Setar
        - Running
        - Reading Books
        
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
